### ISSUE TITLE
Token example is not working

### ISSUE THREAD

**Issue by BladeRunner713** [FuelLabs/sway-libs#193]
### Describe the bug

When I use token example and run 'forc build', I encountered "Trait "Hash" is not implemented for type "AssetId"." Seem like the example doesn't work in beta-test4.

### Steps to reproduce

1. Copy code in token example ([https://github.com/FuelLabs/sway-libs/tree/master/libs/token]). 
2. Add v0.13.1 as dependency.
3. run 'forc build'.

### Minimal reproducible code example

```Rust
use token::{
    _total_assets, 
    _total_supply,
    _name,
    _symbol,
    _decimals
};
use src_20::SRC20;
use std::string::String;

storage {
    total_assets: u64 = 0,
    total_supply: StorageMap<AssetId, u64> = StorageMap {},
    name: StorageMap<AssetId, StorageKey<StorageString>> = StorageMap {},
    symbol: StorageMap<AssetId, StorageKey<StorageString>> = StorageMap {},
    decimals: StorageMap<AssetId, u8> = StorageMap {},
}

impl SRC20 for Contract {
    #[storage(read)]
    fn total_assets() -> u64 {
        _total_assets(storage.total_assets)
    }

    #[storage(read)]
    fn total_supply(asset: AssetId) -> Option<u64> {
        _total_supply(storage.total_supply, asset)
    }

    #[storage(read)]
    fn name(asset: AssetId) -> Option<String> {
        _name(storage.name, asset)
    }

    #[storage(read)]
    fn symbol(asset: AssetId) -> Option<String> {
        _symbol(storage.symbol, asset)
    }

    #[storage(read)]
    fn decimals(asset: AssetId) -> Option<u8> {
        _decimals(storage.decimals, asset)
    }
}
```

### Rust Version

1.72.0 (5680fa18f 2023-08-23)

### Forc Version

0.45.0

### Expected behavior

Successfully build.

**Comment by bitzoic** [comment]
In forc v0.45.0, `AssetId` is simply an alias for a `b256`. If this is not working then there is a bug within the compiler, I will try to replicate this and report it. The following should work as expected:

```rust
storage {
    total_assets: u64 = 0,
    total_supply: StorageMap<b256, u64> = StorageMap {},
    name: StorageMap<b256, StorageKey<StorageString>> = StorageMap {},
    symbol: StorageMap<b256, StorageKey<StorageString>> = StorageMap {},
    decimals: StorageMap<b256, u8> = StorageMap {},
}
```
Please note that in the upcoming release of forc v0.46.0, `AssetId` has been converted into a type as described in the https://github.com/FuelLabs/sway/pull/4955 PR. The only changes that you will be required to implement will be to change these storage variables back to `AssetId`.

**Comment by bitzoic** [comment]
This seems to be an issue with forc 0.45.0. I recommend using forc 0.44.1 until https://github.com/FuelLabs/sway/issues/5105 has been resolved.

**Comment by bitzoic** [comment]
Closing as this has been resolved in the recent release

**Comment by BladeRunner713** [comment]
Hi,

After upgrading to forc 0.46 I still have the same problem. Trait "Hash" is not implemented for type "AssetId".

Here is my code.

`contract;

use token::{
    _total_assets, 
    _total_supply,
    _name,
    _symbol,
    _decimals
};
use src_20::SRC20;
use std::string::String;

storage {
    total_assets: u64 = 0,
    total_supply: StorageMap<AssetId, u64> = StorageMap {},
    name: StorageMap<AssetId, StorageString> = StorageMap {},
    symbol: StorageMap<AssetId, StorageString> = StorageMap {},
    decimals: StorageMap<AssetId, u8> = StorageMap {},
}

impl SRC20 for Contract {
    #[storage(read)]
    fn total_assets() -> u64 {
        _total_assets(storage.total_assets)
    }

    #[storage(read)]
    fn total_supply(asset: AssetId) -> Option<u64> {
        _total_supply(storage.total_supply, asset)
    }

    #[storage(read)]
    fn name(asset: AssetId) -> Option<String> {
        _name(storage.name, asset)
    }

    #[storage(read)]
    fn symbol(asset: AssetId) -> Option<String> {
        _symbol(storage.symbol, asset)
    }

    #[storage(read)]
    fn decimals(asset: AssetId) -> Option<u8> {
        _decimals(storage.decimals, asset)
    }
}`

**Comment by bitzoic** [comment]
> Hi,
> 
> After upgrading to forc 0.46 I still have the same problem. Trait "Hash" is not implemented for type "AssetId".
> 
> Here is my code copied from token example.
> 
> `contract;
> 
> use token::{ _total_assets, _total_supply, _name, _symbol, _decimals }; use src_20::SRC20; use std::string::String;
> 
> storage { total_assets: u64 = 0, total_supply: StorageMap<AssetId, u64> = StorageMap {}, name: StorageMap<AssetId, StorageString> = StorageMap {}, symbol: StorageMap<AssetId, StorageString> = StorageMap {}, decimals: StorageMap<AssetId, u8> = StorageMap {}, }
> 
> impl SRC20 for Contract { #[storage(read)] fn total_assets() -> u64 { _total_assets(storage.total_assets) }
> 
> ```
> #[storage(read)]
> fn total_supply(asset: AssetId) -> Option<u64> {
>     _total_supply(storage.total_supply, asset)
> }
> 
> #[storage(read)]
> fn name(asset: AssetId) -> Option<String> {
>     _name(storage.name, asset)
> }
> 
> #[storage(read)]
> fn symbol(asset: AssetId) -> Option<String> {
>     _symbol(storage.symbol, asset)
> }
> 
> #[storage(read)]
> fn decimals(asset: AssetId) -> Option<u8> {
>     _decimals(storage.decimals, asset)
> }
> ```
> 
> }`

Please be sure to add `std::hash::Hash` to your imports. There were two issues here and one has been resolved. The issue of the required import is being address [here](https://github.com/FuelLabs/sway/issues/5129).

**Comment by bitzoic** [comment]
I opened a PR to add this to the example for now https://github.com/FuelLabs/sway-libs/pull/196
